

// Generated by https://quicktype.io

export interface Song {
  id:               number;
  title:            string;
  artist:           string;
  year:             number;
  genre:            string;
  duration:         string;
  duration_seconds: number;
  album:            string;
  plays:            number;
  language:         Language;
  alt_img?:       string;
}

export enum Language {
  English = "English",
  Spanish = "Spanish",
  French = "French",
  Portuguese = "Portuguese",
  Italian = "Italian",
}
